import {digest} from './engine.mjs';
import {importPolicy} from './policies.mjs';
import {registerContract,submitEvidence,reconcileVerification,generateReport} from './verification.mjs';
export const COMPANY={name:'Northstar Casework',product:'Agency case-management SaaS',scope:'northstar-fictional-production',people:'42 employees · 3 fictional agency tenants',goal:'FedRAMP 20x Class C learning scenario',boundary:'API and worker containers, a PostgreSQL database, object storage, identity integration and a dedicated log archive. Customer devices and agency identity providers are external dependencies.',flow:'Agency user → identity provider → HTTPS API → case worker → encrypted database / attachments. Administrative and application events go to the log archive.',owners:'Maya Chen · Security; Jordan Ellis · Platform; Avery Reed · Assurance',limitation:'Fictional company and synthetic source responses. Real Beacon validation and persistence; no live cloud collection or certification authority.'};
export const DEMO_STEPS=[
 {id:'prepare',title:'Meet the company',action:'Load Northstar workspace',description:'Register the boundary, four policy documents and six precise checks. Everything starts with missing evidence.'},
 {id:'collect',title:'Collect the first evidence',action:'Run simulated collectors',description:'Read canned infrastructure, identity, logging and recovery responses. Normalize facts and run the actual validators.'},
 {id:'draft',title:'Document the gaps',action:'Generate baseline drafts',description:'Pin the failing evidence into a Security Decision Record, Secure Configuration Guide and Ongoing Certification Report draft.'},
 {id:'remediate',title:'Fix and retest',action:'Apply simulated fixes & recollect',description:'Correct encryption, restore log delivery, remove access sooner and pass the recovery exercise. Earlier report snapshots remain unchanged.'},
 {id:'revise',title:'Change the policy',action:'Tighten access removal to 2 hours',description:'The policy changes from four hours to two. Beacon flags the changed policy reference even while the old four-hour assertion still passes.'},
 {id:'rebind',title:'Update the validator',action:'Bind the check to policy v2',description:'Explicitly adopt the new policy version and two-hour threshold. The three-hour observation now fails.'},
 {id:'finish',title:'Retest and refresh the package',action:'Recollect & regenerate drafts',description:'A new one-hour observation passes. Generate updated drafts while preserving baseline versions and the need for independent review.'}
];
const P='northstar-demo-';
const POLICY_DEFS=[
 ['security','Information protection','Case records and attachments must be encrypted at rest. Platform Engineering compares deployed encryption configuration with the approved Terraform plan every day. Key authorization, existing-object coverage and module validation require separate evidence.','KSI-SVC-SIN'],
 ['access','Access removal procedure','People Operations opens a termination ticket at the effective separation time. Identity Engineering disables production access within 4 hours, revokes sessions, checks residual permissions and attaches timestamps. Avery reviews exceptions each business day.','KSI-IAM-ELP'],
 ['logging','Logging and monitoring','Cloud and application audit events must reach the restricted archive. Platform checks configuration and submits a canary event every hour; delivery must occur within 15 minutes. Missing events trigger an investigation. These are Northstar-defined targets.','KSI-MLA-ALA'],
 ['recovery','Recovery procedure','Platform restores a case database into an isolated environment, verifies records and exercises application access. The organizational recovery target is 60 minutes. Security reviews the drill evidence and records unresolved gaps.','KSI-RPL-TRC']
];
export async function demoPolicy(key,tight=false){const row=POLICY_DEFS.find(r=>r[0]===key);if(!row)throw Error('Unknown sample policy');const statement=tight?row[2].replace('4 hours','2 hours'):row[2];const markdown=`# Northstar Casework — ${row[1]}\n\nFICTIONAL TRAINING DOCUMENT — NOT APPROVED\n\nVersion: ${tight?2:1}\nOwner: ${key==='access'?'Maya Chen':'Jordan Ellis'}\nScope: ${COMPANY.scope}\n\n## Commitment and procedure\n${statement}\n\n## Evidence and review\nRetain original source responses, observation timestamps, resource identities, validator versions and review decisions. A policy statement alone is not proof of operation.\n\n## Governance\nOwner approval and independent assessment are pending. Review after material changes and at the organization-defined quarterly review.\n`;
 return {doc_id:P+key,ingest:{source_hash:await digest(markdown),markdown,title:'Northstar · '+row[1],engine:'Beacon fictional fixture',detected_format:'markdown',pages_needing_ocr:[]},statements:[{statement:{statement_id:key+'-commitment',text:statement,heading_path:['Commitment and procedure'],statement_kind:'control_description',classification_confidence:1,classification_reasons:['Author-authored fictional example; not machine extraction']},mappings:[{framework:'FedRAMP 20x',control_id:row[3],title:'Supporting candidate only',source:'Northstar teaching example',relationship:'supporting-candidate',confidence:0.5,url:'https://www.fedramp.gov/2026/providers/20x/key-security-indicators/'}]}]};
}
export const CHECKS=[
 {id:'encryption',title:'Case database encryption',owner:'Jordan Ellis',policy:'security',ksi:'KSI-SVC-SIN',soc:'CC6.1',asset:'case-database',methods:[{id:'runtime',title:'Deployed database is encrypted',field:'encrypted',op:'eq',value:true,source:'Database describe response',rawField:'StorageEncrypted'},{id:'plan',title:'Declared database configuration requires encryption',field:'encrypted',op:'eq',value:true,source:'Terraform plan projection',rawField:'storage_encrypted'}]},
 {id:'logging',title:'Audit events reach the archive',owner:'Maya Chen',policy:'logging',ksi:'KSI-MLA-ALA',soc:'CC7.2',asset:'organization-trail',methods:[{id:'configuration',title:'Trail logging is enabled',field:'logging',op:'eq',value:true,source:'Trail status response',rawField:'IsLogging'},{id:'delivery',title:'A canary reaches the archive within 15 minutes',field:'deliveryMinutes',op:'lte',value:15,source:'Synthetic canary lookup',rawField:'deliveryMinutes'}]},
 {id:'access',title:'Separated worker loses production access',owner:'Maya Chen',policy:'access',ksi:'KSI-IAM-ELP',soc:'CC6.2',asset:'termination-0042',methods:[{id:'removal',title:'Access removal meets the policy deadline',field:'elapsedHours',op:'lte',value:4,source:'HR ticket and identity audit correlation',rawField:'elapsedHours'}]},
 {id:'recovery',title:'Restore test meets the recovery objective',owner:'Jordan Ellis',policy:'recovery',ksi:'KSI-RPL-TRC',soc:'A1.3',asset:'case-restore-drill',methods:[{id:'restore',title:'Successful restore completes within 60 minutes',field:'durationMinutes',op:'lte',value:60,source:'Restore drill result',rawField:'durationMinutes'}]}
];
function policyFor(s,key){return (s.policies||[]).filter(p=>p.docId===P+key).at(-1);}
async function contracts(s,actor,now,onlyAccess=false){for(const c of CHECKS.filter(c=>!onlyAccess||c.id==='access')){const p=policyFor(s,c.policy);await registerContract(s,{contract:{id:P+c.id,title:'Northstar · '+c.title,scopeId:COMPANY.scope,owner:c.owner,maxAgeHours:24,objectives:c.methods.map(m=>({id:m.id,title:m.title,kind:P+c.id+'.'+m.id,subjects:[c.asset],assertions:[{field:m.field,op:m.op,value:c.id==='access'&&p.version===2?2:m.value},...(c.id==='recovery'?[{field:'restoreSucceeded',op:'eq',value:true}]:[])],policyReference:{documentId:p.docId,version:String(p.version),sourceHash:p.sourceHash,locator:'Commitment and procedure'},mappings:[{framework:'FedRAMP 20x',edition:'CR26 2026 · selected supporting candidate',reference:c.ksi},{framework:'SOC 2',edition:'2017 TSC · candidate applicability',reference:c.soc}]}))}},actor,now);}}
// These fixtures never contact a vendor. Normalization is intentionally explicit and inspectable.
export function sourceFixture(check,method,phase,now){const fixed=phase!=='collect';const value=check.id==='encryption'?(method.id==='plan'||fixed):check.id==='logging'?(method.id==='configuration'?true:fixed?2:35):check.id==='access'?(phase==='finish'?1:fixed?3:6):fixed?42:95;let response={[method.rawField]:value};
 if(check.id==='access')response={ticket:'HR-0042',effectiveAt:new Date(now-value*3600000).toISOString(),accessDisabledAt:new Date(now).toISOString()};
 if(check.id==='recovery')response={durationMinutes:value,restoreSucceeded:fixed,recordsVerified:fixed};
 const facts=check.id==='access'?{elapsedHours:(Date.parse(response.accessDisabledAt)-Date.parse(response.effectiveAt))/3600000}:{[method.field]:response[method.rawField],...(check.id==='recovery'?{restoreSucceeded:response.restoreSucceeded}:{})};
 return {response,facts};}
async function collect(s,actor,now,phase){for(const c of CHECKS)for(const m of c.methods){const {response,facts}=sourceFixture(c,m,phase,now);const evidenceId=P+c.id+'-'+m.id;const previous=s.verification.evidence.filter(e=>e.key===evidenceId).at(-1);if(previous&&Date.parse(previous.body.observedAt)>=now)throw Error('Wait for a newer observation time before recollecting.');await submitEvidence(s,{evidence:{id:evidenceId,scopeId:COMPANY.scope,subjectId:c.asset,kind:P+c.id+'.'+m.id,observedAt:new Date(now).toISOString(),source:{type:'test',name:'SIMULATED · '+m.source,version:'northstar-fixture-v1'},facts,content:{synthetic:true,phase,asset:c.asset,operation:m.source,response},citations:[]}},actor,now);}}
async function reports(s,actor,now){const contractIds=CHECKS.map(c=>P+c.id);const phase=s.saasDemo.completed.includes('rebind')?'After policy v2 and corrective retest':'Baseline with known failures';const inputs={
 'fedramp-sdr':{'Decision and scope':`${COMPANY.name}; ${COMPANY.scope}. FICTIONAL TRAINING DRAFT. ${COMPANY.boundary}`,'Applicable requirements':'Selected supporting KSI candidates only: '+CHECKS.map(c=>c.ksi).join(', ')+'. Class C applicability and complete KSI coverage remain unassessed.','Evidence and alternatives':`${phase}. Runtime and declared database state are separate methods. Logging configuration and canary delivery are separate checks. Identity timestamps and restore results test organization-defined targets. See pinned results below.`,'Risk rationale':'Policy text, Terraform intent and successful assertions do not authenticate source evidence. Evaluate population completeness, sample selection, cryptographic module deployment and customer dependencies separately.','Approvers and review date':'Maya Chen (fictional owner). Owner approval and independent assessor review pending.'},
 'fedramp-scg':{'Offering boundary':COMPANY.boundary,'Customer responsibilities':'Configure agency identity federation; assign least-privilege roles; manage customer devices and data classifications. Fictional examples require technical review.','Secure configuration instructions':'Use the approved encrypted database configuration; enable audit logging and verify delivery; disable separated-user access and revoke sessions; execute isolated restore drills.','Validation procedures':'Compare deployed state with declared configuration; time a canary event; correlate separation and disable timestamps; verify restored records and recovery duration.','Exceptions and version history':`${phase}. Preserve baseline findings and policy versions. All sample assertions require source and assessor review.`},
 'fedramp-ocr':{'Offering and reporting period':`${COMPANY.name}. Point-in-time fictional exercise at ${new Date(now).toISOString()}; no continuous operating period established.`,'Certification posture':'Not certified; sample pursuing 20x Class C. Complete rules, all KSIs and independent assessment remain outstanding.','Material changes':phase,'Vulnerabilities and incidents':'Not assessed in this exercise. Missing vulnerability and incident feeds are not zero findings.','Monitoring activities':'Six narrow checks over four sample assets. Collection runs only when the walkthrough is clicked. No hosted scheduler or live source is connected.','Decisions and follow-up':'Review the pinned evidence. Assign unresolved risks to owners, establish authenticated collection, test completeness, validate package schemas and obtain independent conclusions.'}
 };for(const [templateId,sections] of Object.entries(inputs))await generateReport(s,{templateId,contractIds,sections},actor,now);}
export async function advanceSaasDemo(s,input,actor,now){const next=DEMO_STEPS[s.saasDemo?.completed.length||0];if(!next||input.step!==next.id)throw Error('Run the next walkthrough step in order.');
 if(next.id==='prepare'){if((s.verification?.contracts||[]).some(c=>c.body.scopeId===COMPANY.scope||c.key.startsWith(P))||(s.policies||[]).some(p=>p.docId.startsWith(P)))throw Error('Northstar sample identifiers are already in use.');s.saasDemo={id:P+'walkthrough',completed:[],history:[],scopeId:COMPANY.scope,synthetic:true};for(const p of POLICY_DEFS)await importPolicy(s,{report:await demoPolicy(p[0])},actor,now);await contracts(s,actor,now);}
 if(['collect','remediate','finish'].includes(next.id))await collect(s,actor,now,next.id);
 if(next.id==='revise')await importPolicy(s,{report:await demoPolicy('access',true)},actor,now);
 if(next.id==='rebind')await contracts(s,actor,now,true);
 await reconcileVerification(s,actor,now);
 if(['draft','finish'].includes(next.id))await reports(s,actor,now);
 s.saasDemo.completed.push(next.id);s.saasDemo.history.push({step:next.id,at:new Date(now).toISOString(),actor});return {id:s.saasDemo.id,step:next.id,synthetic:true};
}
