import {registerContract,submitEvidence,evaluateContract} from './verification.mjs';
export const STARTERS={encryption:{title:'Encryption stays enabled',field:'encryptionEnabled',op:'eq',type:'boolean',expected:'true'},logging:{title:'Audit logging stays enabled',field:'loggingEnabled',op:'eq',type:'boolean',expected:'true'},offboarding:{title:'Access is removed within four hours',field:'elapsedHours',op:'lte',type:'number',expected:'4'},custom:{title:'My own check',field:'',op:'eq',type:'string',expected:''}};
export function typedValue(value,type){if(type==='boolean'){if(!['true','false'].includes(value))throw Error('Choose Yes or No.');return value==='true';}if(type==='number'){if(!String(value).trim()||!Number.isFinite(Number(value)))throw Error('Enter a valid number.');return Number(value);}if(type!=='string')throw Error('Unknown value type.');if(!String(value).trim())throw Error('Enter a value.');return String(value);}
export function setupContract(form,id){
 const required=['name','scope','owner','subjects','title','field'];for(const k of required)if(!String(form[k]||'').trim())throw Error('Complete the application, scope, owner, assets and check fields.');
 if(['__proto__','constructor','prototype'].includes(form.field.trim()))throw Error('Choose a different fact name.');
 const subjects=form.subjects.split('\n').map(s=>s.trim()).filter(Boolean);if(subjects.length>100||new Set(subjects).size!==subjects.length)throw Error('Use up to 100 unique asset names, one per line.');
 if(!['eq','lte','gte','present'].includes(form.op))throw Error('Choose a supported comparison.');
 const value=form.op==='present'?undefined:typedValue(form.expected,form.type);if(['lte','gte'].includes(form.op)&&typeof value!=='number')throw Error('At most and at least require a number.');
 const hours=Number(form.hours);if(!Number.isInteger(hours)||hours<1||hours>8760)throw Error('Evidence freshness must be 1–8760 whole hours.');
 return {id,title:form.name.trim()+' · '+form.title.trim(),scopeId:form.scope.trim(),owner:form.owner.trim(),maxAgeHours:hours,objectives:[{id:'check-1',title:form.title.trim(),kind:'custom.'+id,subjects,assertions:[{field:form.field.trim(),op:form.op,...(value===undefined?{}:{value})}],mappings:[{framework:'Organization policy',edition:'Owner-defined',reference:form.title.trim(),relationship:'supporting-candidate'}]}]};
}
export async function previewSetup(contract,sample,type){const scratch={},now=Date.now();await registerContract(scratch,{contract},'preview',now);const o=contract.objectives[0];await submitEvidence(scratch,{evidence:{id:'preview',scopeId:contract.scopeId,subjectId:o.subjects[0],kind:o.kind,observedAt:new Date(now).toISOString(),source:{type:'test',name:'Unsaved setup preview'},facts:{[o.assertions[0].field]:typedValue(sample,type)}}},'preview',now);return evaluateContract(scratch,contract.id,now);}
export function collectionRecipe(contract,method){const o=contract.objectives[0];return {instructions:'Populate actual observed facts and timestamp. Do not submit this empty example as evidence. Configure authentication and scheduling separately.',method,contractId:contract.id,mcpTool:'beacon_submit_evidence',arguments:{evidence:{id:'REPLACE_WITH_STABLE_OBSERVATION_ID',scopeId:contract.scopeId,subjectId:o.subjects[0],kind:o.kind,observedAt:'REPLACE_WITH_OBSERVATION_TIMESTAMP',source:{type:method==='AI workspace'?'llm':method==='Manual import'?'human':'external-engine',name:'REPLACE_WITH_SOURCE_NAME'},facts:{[o.assertions[0].field]:null}}}};}
