"use client";
import {useState} from 'react';
import {Upload,Play,Search,Server,ArrowDownToLine,ShieldCheck} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {toast} from 'sonner';
function Badge({value}:any){return <span className={'state-badge '+value.toLowerCase()}>{value}</span>;}
export default function Infrastructure({state,act,busy}:any){
 const data=state.infrastructureView||{boundaries:[],expected:0,observed:0,passing:0,unmanaged:0};
 const [scope,setScope]=useState('all'),[scenario,setScenario]=useState('drift'),[query,setQuery]=useState(''),[detail,setDetail]=useState<any>(null),[last,setLast]=useState<any>(null);
 const boundaries=data.boundaries.filter((b:any)=>scope==='all'||b.manifest.id===scope);
 const rows=boundaries.flatMap((b:any)=>b.rows.map((r:any)=>({...r,boundary:b}))).filter((r:any)=>(r.id+' '+r.type+' '+r.owner+' '+r.boundary.manifest.environment).toLowerCase().includes(query.toLowerCase()));
 async function upload(file:File|undefined){if(!file)return;try{if(file.size>240000)throw new Error('Use a minimized manifest or observation below 240 KB');const x=JSON.parse(await file.text());if(x.schema==='beacon.infrastructure.manifest.v1')await act('infra-register',{manifest:x});else if(x.schema==='beacon.infrastructure.observation.v1')await act('infra-import',{observation:x});else throw new Error('Upload a Beacon manifest or minimized inventory observation. Keep raw Terraform plans on the trusted runner.');}catch(e:any){toast.error(e.message);}}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='beacon-infrastructure-posture.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="infra-workspace"><section className="panel infra-command"><div><span className="eyebrow">INFRASTRUCTURE ASSURANCE</span><h2>What you intended. What you observed.</h2><p>Track declared systems and resource populations. Keep planned configuration separate from runtime evidence.</p></div><label className="button secondary"><Upload size={16}/>Import inventory<input className="sr-only" aria-label="Import infrastructure manifest or minimized observation" type="file" accept=".json" disabled={busy} onChange={e=>{upload(e.target.files?.[0]);e.target.value='';}}/></label></section>
 <div className="metrics"><div className="metric"><span>Expected resources<Server size={16}/></span><strong>{data.expected}</strong><p>Across {data.boundaries.length} declared boundaries</p></div><div className="metric"><span>Observed resources</span><strong>{data.observed}</strong><p>Presence does not imply sufficient evidence</p></div><div className="metric"><span>Passing runtime assertions<ShieldCheck size={16}/></span><strong>{data.passing}</strong><p>Configuration facts · provenance shown separately</p></div><div className="metric"><span>Unregistered observations</span><strong>{data.unmanaged}</strong><p>Investigate scope changes before acceptance</p></div></div>
 <section className="panel infra-demo"><div><strong>Explore the CGE-P capstone</strong><p>Run a simulation of planned and observed configuration. No cloud resources are changed.</p></div><Select value={scenario} onValueChange={setScenario}><SelectTrigger aria-label="Infrastructure scenario"><SelectValue/></SelectTrigger><SelectContent>{['healthy','drift','missing','unknown','stale','recovery'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><button className="button primary" disabled={busy} onClick={async()=>{const result=await act('infra-demo',{scenario});if(result){setLast(result);setScope(result.manifestId);}}}><Play size={15}/>Run scenario</button></section>
 {last&&<div className="source-note"><p>Scenario <strong>{last.scenario}</strong>: {last.result.passing}/{last.result.expected} expected resources passed their configuration assertions. Evidence is explicitly simulated.</p></div>}
 <div className="infra-filters"><label className="search"><Search size={16}/><input aria-label="Search infrastructure" placeholder="Resource, owner, type or environment" value={query} onChange={e=>setQuery(e.target.value)}/></label><Select value={scope} onValueChange={setScope}><SelectTrigger aria-label="Infrastructure boundary"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All declared boundaries</SelectItem>{data.boundaries.map((b:any)=><SelectItem key={b.id} value={b.manifest.id}>{b.manifest.name}</SelectItem>)}</SelectContent></Select><button className="button secondary" onClick={download}><ArrowDownToLine size={15}/>Export posture</button></div>
 {!data.boundaries.length?<div className="panel empty-state"><Server size={28}/><h3>Declare what belongs in scope</h3><p>Import an approved resource manifest and observations, or run the capstone scenario to explore the workflow.</p></div>:<>
 <section className="panel"><Table><TableHeader><TableRow><TableHead>Resource / boundary</TableHead><TableHead>Owner</TableHead><TableHead>Planned</TableHead><TableHead>Observed</TableHead><TableHead>Provenance</TableHead></TableRow></TableHeader><TableBody>{rows.map((r:any)=><TableRow key={r.boundary.id+r.id}><TableCell><button className="claim-link infra-resource" onClick={()=>setDetail({boundaryId:r.boundary.manifest.id,resourceId:r.id})}>{r.id}</button><small className="block muted">{r.boundary.manifest.name} · {r.boundary.manifest.environment}</small></TableCell><TableCell>{r.owner}</TableCell><TableCell><Badge value={r.plannedStatus}/></TableCell><TableCell><Badge value={r.status}/>{r.drift&&<small className="block infra-drift">Plan passed; runtime failed</small>}{!r.checks.length&&<small className="block muted">No implemented checks</small>}</TableCell><TableCell><small>{r.boundary.observed?.provenance||'MISSING'}</small></TableCell></TableRow>)}</TableBody></Table></section>
 {boundaries.map((b:any)=><section className="panel infra-boundary" key={b.id}><div><h3>{b.manifest.name}</h3><p>{b.manifest.provider} · {b.manifest.account} · {b.manifest.region} · manifest v{b.version}</p><small className="mono">{b.hash}</small></div><div><strong>{b.runtime.coverage}% observed</strong><p>Expires after {b.manifest.maxAgeHours} hours</p><small>Latest observation: {b.observed?new Date(b.observed.observation.collectedAt).toLocaleString():'Missing'}</small></div>{b.runtime.unmanaged.length>0&&<div><h4>Outside the approved population</h4>{b.runtime.unmanaged.map((r:any)=><p key={r.id}>{r.id}</p>)}</div>}</section>)}
 </>}
 <p className="panel-footnote">{data.scope||'Declared scope only.'} These are narrow technical assertions, not an organization-wide compliance percentage. The GUI, API, MCP and TUI share these results.</p>
 <Sheet open={!!detail} onOpenChange={open=>{if(!open)setDetail(null);}}><SheetContent className="claim-sheet"><SheetHeader><SheetTitle>Resource assurance</SheetTitle><SheetDescription>Review exactly what was tested, what remains unknown and which observations support the result.</SheetDescription></SheetHeader>{detail&&(()=>{const b=data.boundaries.find((b:any)=>b.manifest.id===detail.boundaryId),r=b?.rows.find((r:any)=>r.id===detail.resourceId);if(!r)return <p>Resource no longer in the current manifest.</p>;return <div className="sheet-section"><h3 className="infra-resource">{r.id}</h3><p>{r.owner} · {b.manifest.environment}</p><div className="infra-filters"><span>Plan <Badge value={r.plannedStatus}/></span><span>Runtime <Badge value={r.status}/></span></div>{r.checks.map((c:any)=><div className="review-card" key={c.id}><h3>{c.title}</h3><Badge value={c.status}/><p>{c.reason}</p><p>{c.limitation}</p>{c.mappings.map((m:any)=><small className="block" key={m.join()}>{m.join(' · ')} · supporting candidate</small>)}</div>)}{!r.checks.length&&<p>This resource is inventoried but has no implemented checks. Its status remains UNKNOWN.</p>}<h3>Observed facts</h3><pre className="infra-json">{JSON.stringify(b.observed?.observation.resources.find((x:any)=>x.id===r.id)?.facts||{},null,2)}</pre><h3>Collection history</h3>{(state.infrastructure?.runs||[]).filter((x:any)=>x.observation.manifestId===b.manifest.id).slice().reverse().slice(0,20).map((x:any)=><div className="review-card" key={x.id}><strong>{x.observation.stage} · {x.provenance}</strong><small className="block">{new Date(x.observation.collectedAt).toLocaleString()}</small><small className="mono">{x.hash}</small></div>)}<p>History retains imported observations. No source authentication or independent assessment is implied.</p></div>;})()}</SheetContent></Sheet>
 </div>;
}
