"use client";
import {useState} from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {typedValue} from '@/lib/beacon/setup.mjs';
function Picker({label,value,options,onChange}:any){return <label>{label}<Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(([id,name]:string[])=><SelectItem value={id} key={id}>{name}</SelectItem>)}</SelectContent></Select></label>;}
export default function ObservationForm({contracts,act,busy}:any){
 const [contractId,setContractId]=useState(''),[objectiveId,setObjectiveId]=useState(''),[subject,setSubject]=useState(''),[source,setSource]=useState(''),[observed,setObserved]=useState(''),[values,setValues]=useState<Record<string,string>>({}),[error,setError]=useState(''),[message,setMessage]=useState('');
 const c=contracts.find((r:any)=>r.key===contractId)?.body,o=c?.objectives.find((o:any)=>o.id===objectiveId);
 const fields:any[]=o?[...new Map(o.assertions.map((a:any)=>[a.field,a])).values()]:[];
 function reset(){setValues({});setSubject('');setMessage('');setError('');}
 async function submit(e:any){e.preventDefault();setError('');setMessage('');try{if(!c||!o||!subject||!source.trim()||!observed)throw Error('Choose a check and asset, and supply the source and observation time.');const date=new Date(observed);if(!Number.isFinite(date.getTime())||date.getTime()>Date.now())throw Error('Use a valid observation time in the past.');const facts=Object.fromEntries(fields.map(a=>[a.field,typedValue(values[a.field]??'',a.op==='present'?'string':typeof a.value)]));const output=await act('verification-evidence',{evidence:{id:crypto.randomUUID(),scopeId:c.scopeId,subjectId:subject,kind:o.kind,source:{type:'human',name:source.trim()},observedAt:date.toISOString(),facts}});if(output){setMessage('Observation saved. Findings and report freshness have been updated. Source review is still required.');setValues({});setObserved('');}else setError('Observation was not saved. Review the error and try again.');}catch(e:any){setError(e.message);}}
 return <section className="panel setup-panel"><h2>Add an observation</h2><p>Record what you actually observed. Beacon supplies the matching scope and evidence format for you.</p>{!contracts.length?<p>Create a check with guided setup first.</p>:<form onSubmit={submit}><div className="setup-fields"><Picker label="Saved check" value={contractId} options={contracts.map((r:any)=>[r.key,r.body.title])} onChange={(id:string)=>{setContractId(id);setObjectiveId('');reset();}}/>{c&&<Picker label="Objective" value={objectiveId} options={c.objectives.map((o:any)=>[o.id,o.title])} onChange={(id:string)=>{setObjectiveId(id);reset();}}/>}{o&&<><Picker label="Observed asset" value={subject} options={o.subjects.map((s:string)=>[s,s])} onChange={setSubject}/><label>Where did you observe this?<input required maxLength={300} placeholder="Cloud console export or reviewed record" value={source} onChange={e=>setSource(e.target.value)}/></label><label>When was it observed? (your local time)<input required type="datetime-local" value={observed} onChange={e=>setObserved(e.target.value)}/></label>{fields.map(a=>typeof a.value==='boolean'&&a.op!=='present'?<Picker key={a.field} label={a.field+' · observed value'} value={values[a.field]||''} options={[["true","Yes"],["false","No"]]} onChange={(v:string)=>setValues({...values,[a.field]:v})}/>:<label key={a.field}>{a.field} · observed value<input required maxLength={12000} type={typeof a.value==='number'&&a.op!=='present'?'number':'text'} step="any" value={values[a.field]||''} onChange={e=>setValues({...values,[a.field]:e.target.value})}/></label>)}</>}</div><p className="setup-note">Manual observations remain unverified imports. Use the advanced importer for collection errors, original source content, citations or period evidence. A passing fact does not establish compliance.</p>{error&&<p role="alert" className="error-banner">{error}</p>}{message&&<p role="status">{message}</p>}<button className="button primary" disabled={busy||!o||!fields.length}>Save observation & evaluate</button></form>}</section>;
}
