"use client";
import {useEffect,useState} from 'react';
import {Upload,FileText,ArrowDownToLine,Search} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {toast} from 'sonner';
import {normalizeMapperReport} from '@/lib/beacon/policies.mjs';
function save(name:string,value:any){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function Policies({policies=[],claims,act,busy}:any){
 const [connected,setConnected]=useState(false),[uploading,setUploading]=useState(false),[docId,setDocId]=useState(''),[selected,setSelected]=useState(''),[framework,setFramework]=useState('All frameworks'),[query,setQuery]=useState(''),[review,setReview]=useState<any>(null),[note,setNote]=useState(''),[claimId,setClaimId]=useState('none');
 useEffect(()=>{fetch('/api/documents/map').then(r=>r.ok?r.json():null).then(d=>setConnected(!!d?.configured)).catch(()=>setConnected(false));},[]);
 const policy=policies.find((p:any)=>p.id===selected)||policies.at(-1);
 const frameworks=[...new Set<string>(policy?.report.statements.flatMap((s:any)=>s.mappings.map((m:any)=>m.framework))||[])].sort();
 const rows=policy?.report.statements.filter((s:any)=>(s.statement.text+' '+s.statement.heading_path.join(' ')).toLowerCase().includes(query.toLowerCase())&&(framework==='All frameworks'||s.mappings.some((m:any)=>m.framework===framework)))||[];
 async function upload(file:File|undefined){
  if(!file||uploading||busy)return;setUploading(true);
  try{
   let report;
   if(file.name.toLowerCase().endsWith('.json')){
    if(file.size>4*1024*1024)throw new Error('Mapper report exceeds 4 MiB');
    report=await normalizeMapperReport(JSON.parse(await file.text()));
   }else{
    if(!connected)throw new Error('Connect the private mapper service for direct document uploads, or import its JSON report.');
    if(file.size>6*1024*1024)throw new Error('Document exceeds 6 MiB');
    if(!docId.trim())throw new Error('Enter a stable document ID to track versions');
    const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));
    const response=await fetch('/api/documents/map',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({docId:docId.trim(),filename:file.name,base64:btoa(binary)})});
    const data=await response.json();if(!response.ok)throw new Error(data.error);report=data.report;
   }
   const saved=await act('policy-import',{report});if(saved){setSelected(saved.id);setFramework('All frameworks');setQuery('');}
  }catch(e:any){toast.error(e.message);}finally{setUploading(false);}
 }
 async function decide(decision:string){if(!review)return;const result=await act('policy-review',{policyId:review.policyId,statementId:review.statementId,mappingIndex:review.index,decision,note,claimId:claimId==='none'?null:claimId});if(result){setReview(null);setNote('');}}
 return <section className="policy-workspace">
  <div className="panel policy-upload"><div><span className="eyebrow">GRC PDF MAPPER</span><h2>Your policies, connected to controls.</h2><p>Extract requirements, inspect proposed mappings, and record why each relationship belongs.</p><small>{connected?'Private mapper connected · PDF, Word, Markdown and text · 6 MiB maximum':'Direct extraction is not connected. Import a JSON report from your GRC PDF Mapper engine.'}</small></div><div className="policy-upload-controls"><label>Stable document ID<input value={docId} onChange={e=>setDocId(e.target.value)} placeholder="pol-access-control" maxLength={160}/></label><label className="button primary"><Upload size={16}/>{uploading?'Processing…':'Upload document or report'}<input type="file" className="sr-only" aria-label="Upload policy document or mapper report" disabled={busy||uploading} accept={connected?'.md,.markdown,.txt,.pdf,.docx,.json':'.json'} onChange={e=>{upload(e.target.files?.[0]);e.target.value='';}}/></label></div></div>
  {!policy?<div className="panel empty-state"><FileText size={28}/><h3>Bring in your first policy</h3><p>Run your mapper against a policy or procedure, then upload its JSON report here. Every proposed relationship starts with a source statement.</p></div>:<>
   <div className="panel policy-toolbar"><div><label className="eyebrow">DOCUMENT VERSION</label><Select value={policy.id} onValueChange={v=>{setSelected(v);setFramework('All frameworks');}}><SelectTrigger aria-label="Document version"><SelectValue/></SelectTrigger><SelectContent>{policies.slice().reverse().map((p:any)=><SelectItem key={p.id} value={p.id}>{p.docId} · v{p.version}</SelectItem>)}</SelectContent></Select></div><div><strong>{policy.report.statements.length}</strong><small>Extracted statements</small></div><div><strong>{frameworks.length}</strong><small>Frameworks with candidates</small></div><button className="button secondary" onClick={()=>save(policy.docId+'-v'+policy.version+'.json',policy)}><ArrowDownToLine size={16}/>Export review record</button></div>
   <div className="policy-context"><div><h3>{policy.report.ingest.title}</h3><p>{policy.limitation}</p><small>Source SHA-256: <span className="mono">{policy.sourceHash}</span></small><small>Extraction: {policy.report.ingest.engine} · Imported report · {new Date(policy.at).toLocaleString()}</small></div><div><strong>{policy.change.added.length} added · {policy.change.removed.length} removed</strong><p>{policy.previousId?'Reviews start fresh for this version. Earlier decisions remain with the previous version.':'First imported version.'}</p>{policy.report.ingest.pages_needing_ocr.length>0&&<p className="policy-warning">OCR review required for pages {policy.report.ingest.pages_needing_ocr.join(', ')}</p>}</div></div>
   {policy.previousId&&<details className="panel policy-changes"><summary>Inspect changed statements</summary><h4>Added</h4>{policy.change.added.map((t:string,i:number)=><p key={i}>{t}</p>)}<h4>Removed</h4>{policy.change.removed.map((t:string,i:number)=><p key={i}>{t}</p>)}</details>}
   <div className="policy-filters"><label className="search"><Search size={16}/><input aria-label="Search policy statements" placeholder="Find a requirement or heading" value={query} onChange={e=>setQuery(e.target.value)}/></label><Select value={framework} onValueChange={setFramework}><SelectTrigger aria-label="Filter policy framework"><SelectValue/></SelectTrigger><SelectContent>{['All frameworks',...frameworks].map(f=><SelectItem key={f} value={f}>{f}</SelectItem>)}</SelectContent></Select></div>
   <section className="panel"><Table><TableHeader><TableRow><TableHead>Source statement</TableHead><TableHead>Proposed mappings</TableHead></TableRow></TableHeader><TableBody>{rows.map((row:any)=><TableRow key={row.statement.statement_id}><TableCell className="policy-statement"><small>{row.statement.heading_path.join(' / ')||'Document body'}{row.statement.page?' · Page '+row.statement.page:''}</small><p>{row.statement.text}</p><span className="state-badge neutral">{row.statement.statement_kind} · {row.statement.strength}</span><small>Classifier score: {Math.round(row.statement.classification_confidence*100)}% · requires review</small><details><summary>Classification reasons</summary>{row.statement.classification_reasons.map((reason:string,i:number)=><p key={i}>{reason}</p>)}</details></TableCell><TableCell><div className="policy-mappings">{row.mappings.map((m:any,index:number)=>{if(framework!=='All frameworks'&&framework!==m.framework)return null;const decision=policy.reviews.filter((r:any)=>r.statementId===row.statement.statement_id&&r.mappingIndex===index).at(-1);return <button key={index} className="policy-mapping" disabled={busy} onClick={()=>{setReview({policyId:policy.id,statementId:row.statement.statement_id,index,mapping:m,text:row.statement.text,history:policy.reviews.filter((r:any)=>r.statementId===row.statement.statement_id&&r.mappingIndex===index)});setNote('');setClaimId(decision?.claimId||'none');}}><strong>{m.framework} · {m.control_id}</strong><small>{m.title}</small><small>{decision?.decision||'Proposed'} · {m.source} · {Math.round(m.confidence*100)}% score</small></button>;})}{!row.mappings.length&&<p>No proposed mappings. Manual analysis required.</p>}</div></TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty-state">No statements match. Empty extraction does not establish coverage.</p>}</section>
   <details className="panel policy-changes"><summary>Extracted document text</summary><pre className="policy-source">{policy.report.ingest.markdown}</pre></details>
  </>}
  <Sheet open={!!review} onOpenChange={open=>{if(!open)setReview(null);}}><SheetContent className="claim-sheet"><SheetHeader><SheetTitle>Review a proposed mapping</SheetTitle><SheetDescription>Accepting a relationship records your mapping judgment. It does not validate operation of the control.</SheetDescription></SheetHeader>{review&&<div className="policy-review"><blockquote>{review.text}</blockquote><h3>{review.mapping.framework} · {review.mapping.control_id}</h3><p>{review.mapping.title}</p><p>Source: {review.mapping.source} · Relationship: {review.mapping.relationship}</p><label>Supporting Beacon claim (optional)<Select value={claimId} onValueChange={setClaimId}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">No claim link</SelectItem>{claims.map((c:any)=><SelectItem key={c.id} value={c.id}>{c.id} · {c.title}</SelectItem>)}</SelectContent></Select></label><label>Reason for your decision<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} rows={5}/></label><div className="policy-filters"><button className="button primary" disabled={busy||!note.trim()} onClick={()=>decide('accepted')}>Accept mapping</button><button className="button secondary" disabled={busy||!note.trim()} onClick={()=>decide('rejected')}>Reject mapping</button></div><h4>Review history</h4>{review.history.map((r:any)=><p key={r.id}><strong>{r.decision}</strong> · {r.note}<small>{r.actor} · {new Date(r.at).toLocaleString()}</small></p>)}</div>}</SheetContent></Sheet>
 </section>;
}
