"use client";
import {useState} from 'react';
import {ArrowRight,Check,Download,PlugZap} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {STARTERS,setupContract,previewSetup,collectionRecipe} from '@/lib/beacon/setup.mjs';
function Choice({label,value,options,onChange}:any){return <label>{label}<Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map((o:any)=><SelectItem key={o[0]} value={o[0]}>{o[1]}</SelectItem>)}</SelectContent></Select></label>;}
function exportRecipe(c:any,method:string){const url=URL.createObjectURL(new Blob([JSON.stringify(collectionRecipe(c,method),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='beacon-collector-recipe.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function Setup({data,act,busy,navigate}:any){
 const [step,setStep]=useState(0),[form,setForm]=useState<any>({name:'',scope:'',owner:'',subjects:'',...STARTERS.encryption,hours:'24'}),[method,setMethod]=useState('Manual import'),[starter,setStarter]=useState('encryption'),[sample,setSample]=useState('true'),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[saved,setSaved]=useState<any>(null),[testing,setTesting]=useState(false),[id]=useState(()=>crypto.randomUUID());
 const update=(k:string,v:string)=>{setForm((f:any)=>({...f,[k]:v}));setResult(null);setError('');};
 function field(key:string,label:string,placeholder='',type='text'){return <label>{label}<input required maxLength={300} type={type} placeholder={placeholder} value={form[key]} onChange={e=>update(key,e.target.value)}/></label>;}
 async function test(){setTesting(true);setError('');try{setResult(await previewSetup(setupContract(form,id),sample,form.type));}catch(e:any){setError(e.message);}finally{setTesting(false);}}
 async function next(){setError('');try{if(step===0&&['name','scope','owner','subjects'].some(k=>!form[k].trim()))throw Error('Add an application, scope, owner and at least one asset.');if(step===2)setupContract(form,id);setStep(step+1);}catch(e:any){setError(e.message);}}
 async function save(){setError('');try{const contract=setupContract(form,id);const output=await act('verification-contract',{contract});if(output)setSaved(contract);else setError('Setup was not saved. Review the error and try again.');}catch(e:any){setError(e.message);}}
 if(saved)return <section className="panel setup-panel"><div className="setup-success"><Check/><span>Check saved · waiting for evidence</span></div><h2>{saved.title}</h2><p>Your test sample was not saved. Submit an actual observation to see the first result.</p><div className="setup-next"><h3>1. Give your source the collection recipe</h3><p>The recipe contains the exact scope, asset and fact names this check expects. {method==='Manual import'?'Use the evidence importer in the verification engine.':'Configure your source to call beacon_submit_evidence using an authorized MCP connection.'}</p><button className="button secondary" onClick={()=>exportRecipe(saved,method)}><Download size={16}/>Download collection recipe</button><h3>2. Connect and schedule your source</h3><p>Authentication and recurring collection still need setup. No credentials are stored by this wizard.</p><h3>3. Review the first observation</h3><p>Beacon tests the submitted facts, flags missing or expired evidence, and retains findings for review.</p><button className="button primary" onClick={()=>navigate('Verification engine')}>Open checks & findings <ArrowRight size={16}/></button></div></section>;
 return <><div className="validation-hero"><PlugZap size={32}/><div><h2>One source. One clear check. Start here.</h2><p>Tell Beacon what should be true. Try a sample, then save your evidence check.</p></div></div><section className="panel setup-panel"><ol className="setup-steps" aria-label="Setup progress">{['Your application','Evidence source','What to check','Try & save'].map((label,i)=><li key={label} aria-current={i===step?'step':undefined}><span>{i<step?<Check size={14}/>:i+1}</span>{label}</li>)}</ol><div className="setup-body" key={step}>
 {step===0&&<><p className="eyebrow">01 / SET THE SCOPE</p><h2>What would you like to keep an eye on?</h2><p>Use the names your team already knows. The scope keeps environments separate.</p><div className="setup-fields">{field('name','Application or infrastructure','Customer portal')}{field('scope','Environment or organization','Production / Acme')}{field('owner','Responsible team or person','Platform security')}<label>Assets to check, one per line<textarea required rows={4} maxLength={30000} placeholder={'production-api\nproduction-database'} value={form.subjects} onChange={e=>update('subjects',e.target.value)}/><small>Each asset needs its own observation. Up to 100 unique names.</small></label></div></>}
 {step===1&&<><p className="eyebrow">02 / CHOOSE A ROUTE</p><h2>Where will the evidence come from?</h2><p>You can start with an import and automate collection later.</p><div className="setup-routes">{[['Manual import','Bring observations from an export or your own collection process.'],['Existing collector','Send normalized facts from an evidence engine or CI job.'],['AI workspace','Use an authorized MCP client in Codex, Cursor or Claude.']].map(([name,description])=><button key={name} aria-pressed={method===name} className="setup-route" onClick={()=>setMethod(name)}><PlugZap size={20}/><strong>{name}</strong><span>{description}</span><small>{method===name?'Selected':'Choose this route'}</small></button>)}</div><p className="setup-note">This selects a setup recipe. It does not connect a vendor account or start a collector. AI-supplied facts receive the same unverified status as other imports.</p></>}
 {step===2&&<><p className="eyebrow">03 / DEFINE THE EXPECTATION</p><h2>What should always be true?</h2><div className="setup-fields"><Choice label="Start with a check" value={starter} options={Object.entries(STARTERS).map(([k,v]:any)=>[k,v.title])} onChange={(k:string)=>{setStarter(k);setForm({...form,...(STARTERS as any)[k]});setSample((STARTERS as any)[k].expected);setResult(null);}}/>{field('title','Check name','Backups finish within 24 hours')}{field('field','Fact to read from your source','backupAgeHours')}<Choice label="Value type" value={form.type} options={[['boolean','Yes / No'],['number','Number'],['string','Text']]} onChange={(v:string)=>update('type',v)}/><Choice label="The value must be" value={form.op} options={[["eq","Equal to"],["lte","At most"],["gte","At least"],["present","Present"]]} onChange={(v:string)=>update('op',v)}/>{form.op!=='present'&&(form.type==='boolean'?<Choice label="Expected value" value={form.expected} options={[["true","Yes"],["false","No"]]} onChange={(v:string)=>update('expected',v)}/>:field('expected','Expected value','',form.type==='number'?'number':'text'))}{field('hours','Evidence expires after (hours)','','number')}</div><p className="setup-note">This starts as an organization-defined check. Add reviewed framework references in the advanced contract editor when applicability is established.</p></>}
 {step===3&&<><p className="eyebrow">04 / SEE HOW IT WORKS</p><h2>Try the check before you save it.</h2><p><strong>{form.name}</strong> · {form.scope} · owner: {form.owner}</p><p>{form.title}: <code>{form.field}</code> {({eq:'equals',lte:'is at most',gte:'is at least',present:'must be present'} as any)[form.op]} {form.op!=='present'&&form.expected}. Evidence expires after {form.hours} hours.</p><div className="setup-fields">{form.type==='boolean'?<Choice label="Sample observed value" value={sample} options={[["true","Yes"],["false","No"]]} onChange={(v:string)=>{setSample(v);setResult(null);}}/>:<label>Sample observed value<input type={form.type==='number'?'number':'text'} value={sample} onChange={e=>{setSample(e.target.value);setResult(null);}}/></label>}</div><button className="button secondary" disabled={testing} onClick={test}>{testing?'Testing…':'Test sample'}</button>{result&&<div className="setup-result" role="status"><strong>{result.checks[0].status==='PASS'?'This sample meets your check.':'This sample needs attention.'}</strong><p>{result.checks[0].reasons.join(' · ')||'The submitted value matches your expectation.'}</p><small>Preview of the first asset only. Nothing saved. Other assets still need evidence; this is not a compliance determination.</small></div>}</>}
 {error&&<p role="alert" className="error-banner">{error}</p>}<div className="setup-footer"><button className="button secondary" disabled={step===0||busy} onClick={()=>{setStep(step-1);setError('');}}>Back</button><span>Step {step+1} of 4</span>{step<3?<button className="button primary" onClick={next}>Continue <ArrowRight size={16}/></button>:<button className="button primary" disabled={busy||testing||!result} onClick={save}>Save check <Check size={16}/></button>}</div></div></section><section className="panel setup-panel"><h2>Your saved checks</h2><p>A saved check waits for evidence. Receiving an import does not authenticate its source.</p>{data?.contracts?.length?data.contracts.map((c:any)=>{const e=data.evaluations.find((e:any)=>e.contractId===c.key);return <button className="setup-saved" key={c.key} onClick={()=>navigate('Verification engine')}><span><strong>{c.body.title}</strong><small>{c.body.scopeId} · {c.body.owner}</small></span><span>{e?.checks.some((x:any)=>x.evidenceId)?'Imports received · review required':'Waiting for evidence'}<ArrowRight size={15}/></span></button>;}):<p className="muted">Your first check will appear here after you save it.</p>}</section></>;
}
