"use client";
import {useState} from 'react';
import {Bell,Download,RefreshCw,FileText,Fingerprint,Upload} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {toast} from 'sonner';
import example from '@/examples/verification/offboarding-contract.json';
function download(name:string,value:any,mime='application/json'){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function Verification({data,act,busy}:any){
 const [kind,setKind]=useState('contract'),[payload,setPayload]=useState(JSON.stringify(example,null,2)),[templateId,setTemplateId]=useState('soc2-workpaper'),[selected,setSelected]=useState<string[]>([]),[sections,setSections]=useState<Record<string,string>>({});
 const v=data||{contracts:[],evaluations:[],alerts:[],reports:[],templates:[]},template=v.templates.find((t:any)=>t.id===templateId);
 function choose(k:string){setKind(k);setPayload(JSON.stringify(k==='contract'?example:k==='evidence'?{evidence:{id:'demo-offboarding-observation',scopeId:'demo-organization',subjectId:'demo-termination-001',kind:'identity.offboarding',observedAt:new Date().toISOString(),source:{type:'test',name:'Synthetic offboarding example',version:'1'},collectionStatus:'OK',facts:{elapsedHours:6,allProductionAccessRemoved:true},content:'Synthetic demonstration. Not organization evidence.'}}:{template:{id:'custom-assurance-record',title:'Custom assurance record',framework:'Customer-defined',edition:'1',sections:['Scope','Evidence','Findings','Review']}},null,2));}
 async function submit(){try{await act('verification-'+kind,JSON.parse(payload));}catch(e:any){toast.error(e.message);}}
 return <>
 <div className="validation-hero"><Fingerprint size={36}/><div><h2>Connect a fact to every obligation it supports.</h2><p>Versioned contracts, explicit populations, correlated findings and reports with traceable inputs.</p></div><button className="button primary" disabled={busy} onClick={()=>act('verification-reconcile')}><RefreshCw size={16}/>Reconcile now</button></div>
 <div className="source-note"><Bell size={19}/><p>Diagnostic workspace · imports and policy interpretations require review. Alerts remain local; external delivery is not configured. Last reconciliation: {v.lastReconciled?new Date(v.lastReconciled).toLocaleString():'not run'}. Scheduled checks require the portable watcher or an external scheduler.</p></div>
 <section className="panel"><div className="panel-heading"><div><h2>Correlated findings</h2><p>Failures, monitoring gaps and observed recovery retain their evidence and affected obligations.</p></div><span className="subtle-pill">{v.alerts.filter((a:any)=>a.body.state==='OPEN').length} open</span></div>
 {v.alerts.length?<Table><TableHeader><TableRow><TableHead>Subject / scope</TableHead><TableHead>Signal</TableHead><TableHead>Impact</TableHead><TableHead>State</TableHead><TableHead>Inspect</TableHead></TableRow></TableHeader><TableBody>{v.alerts.map((a:any)=><TableRow key={a.id}><TableCell>{a.body.subjectId}<small className="block muted">{a.body.scopeId}</small></TableCell><TableCell>{a.body.categories.join(', ')||'Assertions now pass'}<small className="block muted">{a.body.kind}</small></TableCell><TableCell>{a.body.checks.length} objectives · {a.body.affectedReports.length} report versions</TableCell><TableCell><span className="subtle-pill">{a.body.state}</span><small className="block muted">Review required</small></TableCell><TableCell><button className="text-button" onClick={()=>download('finding-'+a.id+'.json',a)}>Evidence trail <Download size={14}/></button></TableCell></TableRow>)}</TableBody></Table>:<p className="panel-copy">No correlated findings yet. Register a contract to expose missing evidence, then submit an observation to test its assertions.</p>}
 </section>
 <section className="panel"><div className="panel-heading"><div><h2>Evidence contracts</h2><p>A passing assertion tests submitted facts. It does not establish source authenticity or framework compliance.</p></div></div>
 {v.evaluations.map((e:any)=><details key={e.contractId} className="panel-copy"><summary><strong>{e.contractId}</strong> · {e.configurationStatus} · {e.passing}/{e.expected} assertions</summary><Table><TableHeader><TableRow><TableHead>Objective / subject</TableHead><TableHead>Result</TableHead><TableHead>Supporting mappings</TableHead><TableHead>Evidence</TableHead></TableRow></TableHeader><TableBody>{e.checks.map((c:any)=><TableRow key={c.objectiveId+c.subjectId}><TableCell>{c.title}<small className="block muted">{c.subjectId}</small></TableCell><TableCell>{c.status}<small className="block muted">{c.reasons.join('; ')}</small></TableCell><TableCell>{c.mappings.map((m:any)=>`${m.framework} ${m.edition}: ${m.reference}`).join(' · ')}</TableCell><TableCell>{c.provenance}<small className="block mono">{c.evidenceHash?.slice(0,16)||'Missing'}</small></TableCell></TableRow>)}</TableBody></Table></details>)}
 <div className="mcp-grid"><div className="mcp-form"><label>Import type<Select value={kind} onValueChange={choose}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['contract','evidence','template'].map(k=><SelectItem key={k} value={k}>{k}</SelectItem>)}</SelectContent></Select></label><p>The example models a six-hour access removal against a four-hour target. Its framework mappings are candidates. Change the values to inspect failure, recovery and stale reports.</p><label className="button secondary upload-button"><Upload size={16}/>Load JSON file<input type="file" accept=".json,application/json" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>150000)toast.error('Use a JSON envelope under 150 KB');else setPayload(await f.text());}e.target.value='';}}/></label><button className="button primary" disabled={busy} onClick={submit}>Save {kind}</button></div><textarea aria-label="Verification JSON payload" className="code-output mono" rows={14} value={payload} onChange={e=>setPayload(e.target.value)}/></div>
 </section>
 <section className="panel"><div className="panel-heading"><div><h2>Report studio</h2><p>{v.templates.length} versioned section blueprints. Drafts preserve missing inputs and evidence snapshots.</p></div><FileText size={21}/></div>
 <div className="mcp-grid"><div className="mcp-form"><label>Report blueprint<Select value={templateId} onValueChange={id=>{setTemplateId(id);setSections({});}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{v.templates.map((t:any)=><SelectItem key={t.id} value={t.id}>{t.framework} · {t.title}</SelectItem>)}</SelectContent></Select></label><p>{template?.edition}</p><strong>Include contracts from one scope</strong>{v.contracts.map((c:any)=><label key={c.key}><input type="checkbox" checked={selected.includes(c.key)} onChange={e=>setSelected(e.target.checked?[...selected,c.key]:selected.filter(id=>id!==c.key))}/> {c.body.title} · {c.body.scopeId}</label>)}<button className="button primary" disabled={busy||!selected.length} onClick={()=>act('verification-report',{templateId,contractIds:selected,sections})}>Generate versioned draft</button><p>JSON and Markdown export. Official submission-schema validation, independent conclusions and signatures are pending.</p></div><div className="form-stack">{template?.sections.map((s:string)=><details key={s}><summary>{s} {sections[s]?.trim()?'· supplied':'· missing'}</summary><textarea aria-label={s} rows={4} value={sections[s]||''} onChange={e=>setSections({...sections,[s]:e.target.value})}/></details>)}</div></div>
 </section>
 <section className="panel"><div className="panel-heading"><h2>Report history</h2><span className="subtle-pill">Drafts · no submission authority</span></div>{v.reports.slice().reverse().map((r:any)=><details key={r.id} className="panel-copy"><summary><strong>{r.body.title}</strong> · v{r.version} · {r.needsRefresh?'Evidence changed':'Snapshot current'} · {r.body.missingSections.length} missing sections</summary><p>{r.body.scopeId} · {new Date(r.at).toLocaleString()}</p><div className="trust-toolbar"><button className="button secondary" onClick={()=>download(r.id+'.json',r)}>Download JSON</button><button className="button secondary" onClick={()=>download(r.id+'.md',r.body.markdown,'text/markdown')}>Download Markdown</button></div><pre className="code-output">{r.body.markdown}</pre></details>)}{!v.reports.length&&<p className="panel-copy">Generated drafts will appear here with their pinned contract and evidence hashes.</p>}</section>
 </>;
}
